### PR TITLE
Migrate to WDC V2.

### PR DESCRIPTION
**Pull request by kenji1984**
Changed deprecated WDC V1 api calls to WDC V2.
Fix issue where log off is not logging off.
Fix issue where datetime column always return null data.
Fix issue where most columns are being categorized as Dimension when they're Measure. Column headers are retrieved using new /api/bo-schema instead of /api/bo-data.

### CODE REVIEW

**Comment by kenji1984** [comment]
I have never use Git with other people so apologize if I did things incorrectly. I noticed this repository is not maintained anymore and it didn't work with my SAP universe so I made some changes to it.

**Comment by tfoldi** [comment]
@TheDago , @csireszabolcs , are you okay with this? 

Thanks for the contribution @kenji1984

**Review by csireszabolcs — APPROVED** [review]
Looks great, thanks for the contribution.

**Comment by kenji1984** [comment]
Hey I noticed you just merged my most recent change. I changed a lot things for my own needs so not sure if it fits with your original goal anymore. I thought you can only see the changes if I do a pull request. I’ve never collaborated before so apologize if I’m doing things wrong.

**Pull request merged**
